#FROM docker.io/fengyunpan/kubernetes-node:v1.9.6.2
#FROM kubernetes-node:pfy
FROM registry.fedoraproject.org/fedora:27

ENV container=docker

ENV NAME=kubernetes-kubelet VERSION=0 RELEASE=8 ARCH=x86_64
LABEL bzcomponent="$NAME" \
        name="$FGC/$NAME" \
        version="$VERSION" \
        release="$RELEASE.$DISTTAG" \
        architecture="$ARCH" \
        atomic.type='system' \
        maintainer="FengyunPan <pan_feng_yun@163.com>"

# Containerized kubelet requires nsenter
RUN dnf -y --setopt=tsflags=nodocs update && dnf clean all && dnf -y install dnf-plugins-core && dnf config-manager --add-repo  https://download.docker.com/linux/fedora/docker-ce.repo && dnf config-manager --set-enabled docker-ce-edge && dnf config-manager --set-enabled docker-ce-test && dnf install -y --setopt=tsflags=nodocs docker-ce  && dnf install -y /rpms/kubernetes-client-1.9.6.2-1.el7.x86_64.rpm && dnf install -y --setopt=tsflags=nodocs /rpms/kubernetes-node-1.9.6.2-1.el7.x86_64.rpm findutils  util-linux ethtool systemd-udev e2fsprogs xfsprogs && dnf clean all

LABEL RUN /usr/bin/docker run -d --privileged --net=host --pid=host -v /:/rootfs:ro -v /sys:/sys:rw -v /var/run:/var/run:rw -v /run:/run:rw -v /var/lib/docker:/var/lib/docker:rw -v /var/lib/kubelet:/var/lib/kubelet:slave -v /var/log/containers:/var/log/containers:rw

COPY launch.sh /usr/bin/kubelet-docker.sh

COPY manifest.json tmpfiles.template service.template config.json.template /exports/

RUN mkdir -p /exports/hostfs/etc/cni/net.d && \
    mkdir -p /exports/hostfs/etc/kubernetes && \
    cp /etc/kubernetes/{config,kubelet} /exports/hostfs/etc/kubernetes

ENTRYPOINT ["/usr/bin/kubelet-docker.sh"]
